In [1]:
import pandas as pd

s1 = pd.Series([10, 20, 30, 40, 50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [2]:
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [4]:
print(s1.values)

[10 20 30 40 50]


In [15]:
import numpy as np

s1 = pd.Series(['a', 'b', 'c', 1, 2, 3.3, np.nan])
print(s1)

0      a
1      b
2      c
3      1
4      2
5    3.3
6    NaN
dtype: object


In [20]:
indexA = ['a', 'b', 'c', 'd', 'e']

print(type(np.nan))
print(type(None))

indexSetSeries = pd.Series([1, 2, 3, 4, np.nan], index = indexA)
print(indexSetSeries)

<class 'float'>
<class 'NoneType'>
a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64


In [21]:
dic  = {'a':1, 'b':2, 'c':3, 'd':4, 'e':np.nan}
print(dic)

dicSeries = pd.Series(dic)
print(dicSeries)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': nan}
a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64


In [22]:
# quiz

quizDic  = {'Califonia':np.nan, 
            'Ohio':35000,
            'Texas':71000,
            'Oregon':16000,
            'Utah':5000}
            
quizSeries = pd.Series(quizDic)
print(quizSeries)

Califonia        NaN
Ohio         35000.0
Texas        71000.0
Oregon       16000.0
Utah          5000.0
dtype: float64


In [26]:
dataArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
indexDataArray = pd.date_range('2019-09-21', end = '2019-09-24')
#indexDataArray = pd.date_range('2019-09-21', periods = 4)
colList = ['Park', 'Su', 'Bin']

dataFrame = pd.DataFrame(dataArray, index = indexDataArray, columns=colList)
print(dataFrame)

            Park  Su  Bin
2019-09-21     1   2    3
2019-09-22     4   5    6
2019-09-23     7   8    9
2019-09-24    10  11   12
DatetimeIndex(['2019-09-21', '2019-09-22', '2019-09-23', '2019-09-24'], dtype='datetime64[ns]', freq='D')
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Index(['Park', 'Su', 'Bin'], dtype='object')


In [30]:
dic = {'연도' : [2015, 2016, 2017, 2018, 2019],
        '지사' : ['한국', '미국', '일본', '영국', '중국'],
        '고객 수' : [200, 300, 400, 500, 600]}

dataFrame = pd.DataFrame(dic)
print(dataFrame)

dataFrame = pd.DataFrame(dic, columns=['지사', '고객 수', '연도'])
print(dataFrame)

print(dataFrame.index)
print(dataFrame.values)
print(dataFrame.columns)

     연도  지사  고객 수
0  2015  한국   200
1  2016  미국   300
2  2017  일본   400
3  2018  영국   500
4  2019  중국   600
   지사  고객 수    연도
0  한국   200  2015
1  미국   300  2016
2  일본   400  2017
3  영국   500  2018
4  중국   600  2019
RangeIndex(start=0, stop=5, step=1)
[['한국' 200 2015]
 ['미국' 300 2016]
 ['일본' 400 2017]
 ['영국' 500 2018]
 ['중국' 600 2019]]
Index(['지사', '고객 수', '연도'], dtype='object')


In [47]:
#quiz

arr = np.random.rand(6, 4)
dateIndex = pd.date_range('2019-09-01', end = '2019-09-06')
colList = ['A', 'B', 'C', 'D']

dataFrame = pd.DataFrame(arr, index = dateIndex, columns = colList)
print(dataFrame)

                   A         B         C         D
2019-09-01  0.569822  0.767173  0.221062  0.807301
2019-09-02  0.157070  0.593010  0.677810  0.069134
2019-09-03  0.159709  0.595880  0.555242  0.297333
2019-09-04  0.313691  0.883843  0.942295  0.061997
2019-09-05  0.181495  0.256641  0.211074  0.370155
2019-09-06  0.407090  0.907141  0.081979  0.534371


In [53]:
import pandas as pd
from pandas import Series
# from pd import Series
# import 문에서 pandas를 pd로 as를 해도
# from 에서는 라이브러리 정식 명칭을 가져와야함.