In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("data/thoraric_surgery.csv")
df[0:10]

A1  A2    A3    A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15  A16  \
0  293   1  3.80  2.80   0   0   0   0   0    0   12    0    0    0    1    0   
1    1   2  2.88  2.16   1   0   0   0   1    1   14    0    0    0    1    0   
2    8   2  3.19  2.50   1   0   0   0   1    0   11    0    0    1    1    0   
3   14   2  3.98  3.06   2   0   0   0   1    1   14    0    0    0    1    0   
4   17   2  2.21  1.88   0   0   1   0   0    0   12    0    0    0    1    0   
5   18   2  2.96  1.67   0   0   0   0   0    0   12    0    0    0    1    0   
6   35   2  2.76  2.20   1   0   0   0   1    0   11    0    0    0    0    0   
7   42   2  3.24  2.52   1   0   0   0   1    0   12    0    0    0    1    0   
8   65   2  3.15  2.76   1   0   1   0   1    0   12    0    0    0    1    0   
9  111   2  4.48  4.20   0   0   0   0   0    0   12    0    0    0    1    0   

   A17  Class  
0   62      0  
1   60      0  
2   66      1  
3   80      1  
4   56      0  
5   61      0  
6   76      0  
7   63      1  
8   59      0  
9   55      0

In [11]:
dataArr = df.values
dataArr

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [55]:
from sklearn.model_selection import train_test_split 

train, test = train_test_split(dataArr, test_size = 0.2)
xTrain = train[:, 0:17] # 학습 데이터
yTrain = train[:, 17] # 정답

xTest = train[:, 0:17] # 테스트용 데이터
yTest = train[:, 17] # 테스트용 정답

In [56]:
xTrain

array([[ 45.  ,   3.  ,   3.56, ...,   1.  ,   0.  ,  60.  ],
       [234.  ,   3.  ,   2.6 , ...,   1.  ,   0.  ,  58.  ],
       [230.  ,   3.  ,   2.64, ...,   1.  ,   0.  ,  65.  ],
       ...,
       [166.  ,   3.  ,   3.2 , ...,   1.  ,   0.  ,  54.  ],
       [141.  ,   2.  ,   2.16, ...,   1.  ,   0.  ,  63.  ],
       [184.  ,   3.  ,   2.8 , ...,   1.  ,   0.  ,  56.  ]])

In [57]:
yTrain[0:10]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
from keras.models import Sequential
from keras.layers import Dense

# 딥러닝 모델 Sequential
model = Sequential()

# 2개의 층 추가
# Dense(노드 수, input_dim = 데이터 갯수, activation = 활성화 함수 이름)
model.add(Dense(30, input_dim = 17, activation = "relu"))

# 출력층
model.add(Dense(1, activation = "sigmoid"))

In [50]:
# 학습 환경 설정
# loss : 한번 신경망이 실행 될 때 마다 오차 값을 추적하는 함수
# mean_squared_error : 평균 제곱 오차
# optimizer : 오차를 어떻게 줄여 나갈지 정하는 함수 (가중치 설정 옵션)
# adam : 뭐지? 구글링 해봐야할듯 ㅇㅇ 강의에서 안 알려주네
# metrics : 학습과 테스트 단계에서 모델을 평가하기 위한 성능 기준 설정
# accuracy : 정확도를 기준으로 함
model.compile(loss = "mean_squared_error", 
              optimizer = "adam", 
              metrics = ["accuracy"])

In [51]:
# 데이터를 이용해 학습 시작
# epochs : 몇번을 학습 할건지? -> 학습 횟수
# 학습 할수록 오차 loss가 줄어들고 정확도 accuracy가 증가함
# batch_size : 한번에 몇개의 데이터로 학습 할건지? 
model.fit(xTrain, yTrain, epochs = 30, batch_size = 10)

Epoch 1/30
376/376 [==============================] - 0s 303us/step - loss: 0.7137 - accuracy: 0.2819
Epoch 2/30
376/376 [==============================] - 0s 124us/step - loss: 0.6447 - accuracy: 0.3511
Epoch 3/30
376/376 [==============================] - 0s 105us/step - loss: 0.2842 - accuracy: 0.7021
Epoch 4/30
376/376 [==============================] - 0s 95us/step - loss: 0.1622 - accuracy: 0.8378
Epoch 5/30
376/376 [==============================] - 0s 97us/step - loss: 0.1622 - accuracy: 0.8378
Epoch 6/30
376/376 [==============================] - 0s 96us/step - loss: 0.1622 - accuracy: 0.8378
Epoch 7/30
376/376 [==============================] - 0s 94us/step - loss: 0.1622 - accuracy: 0.8378
Epoch 8/30
376/376 [==============================] - 0s 99us/step - loss: 0.1622 - accuracy: 0.8378
Epoch 9/30
376/376 [==============================] - 0s 94us/step - loss: 0.1622 - accuracy: 0.8378
Epoch 10/30
376/376 [==============================] - 0s 101us/step - loss: 0.1622 - ac

In [58]:
# 모델이 얼마나 정확한지 예측 점검
# 해당 데이터에 대해 오차와 정확도가 출력됨
model.evaluate(xTest, yTest) # 데이터와 정답

376/376 [==============================] - 0s 59us/step


[0.14095744688777215, 0.8590425252914429]

In [62]:
# 모델을 이용해 데이터를 이용해 예측 및 결과 출력
result = model.predict_classes(xTest)
result.ravel() # 무슨 다 죽어 ㅠㅠㅠㅋㅋㅋㅋㅋ 1이 없네

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [65]:
resultDt = pd.DataFrame({
    "result" : result.ravel(), 
    "answer" : yTest.astype(int)
})

resultDt[0:10]

result  answer
0       0       0
1       0       0
2       0       1
3       0       0
4       0       0
5       0       0
6       0       0
7       0       0
8       0       0
9       0       0